# Generated by Django 4.0.3 on 2022-03-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('admin_permisions', 'Admin Permission'), ('student_permisions', 'Student Permission')]},
        ),
    ]
