# Generated by Django 4.0.3 on 2022-03-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('admin_permisions', 'Admin Permission'), ('user_prmission', 'User Permission')]},
        ),
    ]
