# Generated by Django 4.0.3 on 2022-03-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('desc', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('created_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_date', models.DateField()),
                ('updated_by', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.category')),
            ],
        ),
    ]
