# Generated by Django 4.0.3 on 2022-03-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_product_created_by_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('admin_permisions', 'Admin Permission'), ('user_prmission', 'User Permission')]},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
    ]
